services:
  minio:
    image: minio/minio
    container_name: nest-minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'

    volumes:
      - minio_data:/data

volumes:
  minio_data:
